/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CoolButton {
        "active"?: boolean | string;
        "color"?: string;
        "lg"?: boolean | string;
        "loading"?: string;
        "outline"?: boolean | string;
        "sm"?: boolean | string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLCoolButtonElement extends Components.CoolButton, HTMLStencilElement {
    }
    var HTMLCoolButtonElement: {
        prototype: HTMLCoolButtonElement;
        new (): HTMLCoolButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cool-button": HTMLCoolButtonElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CoolButton {
        "active"?: boolean | string;
        "color"?: string;
        "lg"?: boolean | string;
        "loading"?: string;
        "outline"?: boolean | string;
        "sm"?: boolean | string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "cool-button": CoolButton;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cool-button": LocalJSX.CoolButton & JSXBase.HTMLAttributes<HTMLCoolButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
